(() => {
'use strict';
const $=id=>document.getElementById(id);
const E={
 toolbar:$('toolbarWrap'),toolsToggle:$('toolsToggleBtn'),newBtn:$('newBtn'),importBtn:$('importBtn'),saveBtn:$('saveBtn'),addPage:$('addPageBtn'),delPage:$('delPageBtn'),prev:$('prevBtn'),next:$('nextBtn'),pageLabel:$('pageLabel'),
 imageBtn:$('imageBtn'),color:$('colorPicker'),undo:$('undoBtn'),redo:$('redoBtn'),deleteSel:$('deleteSelectedBtn'),clear:$('clearPageBtn'),penW:$('penWidth'),highW:$('highlightWidth'),eraserW:$('eraserWidth'),textSize:$('textSize'),zoomOut:$('zoomOutBtn'),zoomIn:$('zoomInBtn'),zoomInput:$('zoomInput'),applyZoom:$('applyZoomBtn'),fit:$('fitBtn'),zoomLabel:$('zoomLabel'),toolLabel:$('toolLabel'),status:$('status'),selectionStatus:$('selectionStatus'),
 empty:$('emptyState'),emptyNew:$('emptyNewBtn'),emptyImport:$('emptyImportBtn'),scroll:$('scrollArea'),stage:$('pageStage'),pdf:$('pdfCanvas'),overlay:$('overlayCanvas'),pdfInput:$('pdfInput'),imageInput:$('imageInput'),newDialog:$('newDialog'),newForm:$('newForm'),pageSize:$('pageSizeSelect'),createPdf:$('createPdfBtn'),textDialog:$('textDialog'),textForm:$('textForm'),textInput:$('textInput'),cancelText:$('cancelTextBtn'),toast:$('toast')
};
const ctx=E.pdf.getContext('2d'), octx=E.overlay.getContext('2d');
const S={pdfDoc:null,sourceBytes:null,pages:[],page:0,zoom:1,fitMode:true,tool:'select',currentStroke:null,selected:null,drag:null,undo:[],redo:[],filename:'edited.pdf',renderId:0,pendingText:null,imagePending:null};
const PAGE_SIZES={'Letter - Portrait':[612,792],'Letter - Landscape':[792,612],'A4 - Portrait':[595,842],'A4 - Landscape':[842,595],'Square':[612,612]};
let pdfjsPromise=null,pdflibPromise=null;
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s);});}
async function ensurePdfJs(){if(window.pdfjsLib)return window.pdfjsLib;if(!pdfjsPromise)pdfjsPromise=(async()=>{for(const src of ['https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js']){try{await loadScript(src);if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc=src.includes('cdnjs')?'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js':'https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';return window.pdfjsLib;}}catch(_){}}throw new Error('PDF.js failed to load');})();return pdfjsPromise;}
async function ensurePdfLib(){if(window.PDFLib)return window.PDFLib;if(!pdflibPromise)pdflibPromise=(async()=>{for(const src of ['https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js','https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js']){try{await loadScript(src);if(window.PDFLib)return window.PDFLib;}catch(_){}}throw new Error('pdf-lib failed to load');})();return pdflibPromise;}
function toast(m){E.toast.textContent=m;E.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.add('hidden'),2200)}
function page(){return S.pages[S.page]}
function hasDoc(){return !!(S.pdfDoc||S.pages.length)}
function clone(v){return structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v))}
function saveUndo(){S.undo.push(clone(S.pages));if(S.undo.length>60)S.undo.shift();S.redo=[];updateUI();scheduleRecovery()}
function updateUI(){const on=hasDoc(),n=S.pages.length;E.saveBtn.disabled=!on;E.addPage.disabled=!on;E.delPage.disabled=!on||n<=1;E.prev.disabled=!on||S.page<=0;E.next.disabled=!on||S.page>=n-1;E.imageBtn.disabled=!on;E.clear.disabled=!on;E.zoomIn.disabled=!on;E.zoomOut.disabled=!on;E.applyZoom.disabled=!on;E.fit.disabled=!on;E.undo.disabled=!S.undo.length;E.redo.disabled=!S.redo.length;E.deleteSel.disabled=S.selected==null;E.pageLabel.textContent=`Page ${on?S.page+1:0} / ${n}`;E.zoomLabel.textContent=`Zoom ${Math.round(S.zoom*100)}%`;E.zoomInput.value=Math.round(S.zoom*100);E.toolLabel.textContent=`Tool: ${S.tool[0].toUpperCase()+S.tool.slice(1)}`;E.status.textContent=on?`${S.pages.reduce((a,p)=>a+p.annotations.length,0)} editable edit(s). Recovery autosave is ON.`:'Open or create a PDF to begin.';}
function setTool(t){S.tool=t;S.selected=null;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));E.overlay.style.cursor=t==='text'?'text':t==='pan'?'grab':t==='select'?'default':'crosshair';updateUI();drawOverlay()}
function closeTools(){if(innerWidth<=700){E.toolbar.classList.remove('open');E.toolsToggle.setAttribute('aria-expanded','false')}}
E.toolsToggle.addEventListener('click',()=>{const o=E.toolbar.classList.toggle('open');E.toolsToggle.setAttribute('aria-expanded',String(o))});
function showEditor(){E.empty.classList.add('hidden');E.scroll.classList.remove('hidden');}
function showEmpty(){E.empty.classList.remove('hidden');E.scroll.classList.add('hidden');}
async function importFile(file){if(!file)return;try{toast('Opening PDF…');const pdfjs=await ensurePdfJs();const ab=await file.arrayBuffer();S.sourceBytes=new Uint8Array(ab);S.pdfDoc=await pdfjs.getDocument({data:S.sourceBytes.slice()}).promise;S.pages=[];for(let i=0;i<S.pdfDoc.numPages;i++){const p=await S.pdfDoc.getPage(i+1);const v=p.getViewport({scale:1});S.pages.push({kind:'source',sourceIndex:i,width:v.width,height:v.height,rotation:0,annotations:[]});}S.page=0;S.filename=file.name.replace(/\.pdf$/i,'')+'-edited.pdf';S.undo=[];S.redo=[];S.selected=null;S.fitMode=true;showEditor();await render();updateUI();scheduleRecovery();closeTools();toast('PDF loaded.');}catch(err){console.error(err);toast('Could not open PDF. Check your connection and try again.')}}
async function createBlank(){const size=PAGE_SIZES[E.pageSize.value]||PAGE_SIZES['Letter - Portrait'];S.pdfDoc=null;S.sourceBytes=null;S.pages=[{kind:'blank',width:size[0],height:size[1],rotation:0,annotations:[]}];S.page=0;S.filename='new_pdf.pdf';S.undo=[];S.redo=[];S.fitMode=true;showEditor();await render();scheduleRecovery();updateUI();closeTools();}
function openNewDialog(){if(E.newDialog.showModal)E.newDialog.showModal();else createBlank();}
E.newBtn.onclick=E.emptyNew.onclick=openNewDialog;E.importBtn.onclick=E.emptyImport.onclick=()=>E.pdfInput.click();E.pdfInput.onchange=()=>{const f=E.pdfInput.files[0];E.pdfInput.value='';importFile(f)};
E.newForm.addEventListener('submit',e=>{e.preventDefault();if(E.newDialog.open)E.newDialog.close();createBlank()});
function fitScale(p){const w=Math.max(120,E.scroll.clientWidth-20),h=Math.max(120,E.scroll.clientHeight-20);return Math.min(w/p.width,h/p.height,1.5)}
async function render(){if(!hasDoc())return;const id=++S.renderId,p=page();if(S.fitMode)S.zoom=fitScale(p);const cssW=Math.max(1,p.width*S.zoom),cssH=Math.max(1,p.height*S.zoom),dpr=Math.min(devicePixelRatio||1,2.5);for(const c of [E.pdf,E.overlay]){c.width=Math.round(cssW*dpr);c.height=Math.round(cssH*dpr);c.style.width=cssW+'px';c.style.height=cssH+'px';}E.stage.style.width=cssW+'px';E.stage.style.height=cssH+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cssW,cssH);ctx.fillStyle='white';ctx.fillRect(0,0,cssW,cssH);if(p.kind==='source'&&S.pdfDoc){try{const pg=await S.pdfDoc.getPage(p.sourceIndex+1);if(id!==S.renderId)return;const vp=pg.getViewport({scale:S.zoom,rotation:p.rotation||0});await pg.render({canvasContext:ctx,viewport:vp,transform:dpr!==1?[dpr,0,0,dpr,0,0]:null}).promise;}catch(err){console.error(err);toast('Page render failed.')}}drawOverlay();updateUI()}
function drawOverlay(){if(!hasDoc())return;const p=page(),dpr=Math.min(devicePixelRatio||1,2.5),w=p.width*S.zoom,h=p.height*S.zoom;octx.setTransform(dpr,0,0,dpr,0,0);octx.clearRect(0,0,w,h);for(let i=0;i<p.annotations.length;i++){const a=p.annotations[i];octx.save();if(a.type==='stroke'||a.type==='highlight'){octx.strokeStyle=a.color;octx.globalAlpha=a.type==='highlight'?0.35:1;octx.lineWidth=a.width*S.zoom;octx.lineCap='round';octx.lineJoin='round';octx.beginPath();a.points.forEach((pt,j)=>j?octx.lineTo(pt.x*S.zoom,pt.y*S.zoom):octx.moveTo(pt.x*S.zoom,pt.y*S.zoom));octx.stroke();}else if(a.type==='text'){octx.fillStyle=a.color;octx.font=`${a.size*S.zoom}px Arial`;octx.textBaseline='top';a.text.split('\n').forEach((line,j)=>octx.fillText(line,a.x*S.zoom,(a.y+j*a.size*1.2)*S.zoom));}else if(a.type==='image'&&a.img){octx.drawImage(a.img,a.x*S.zoom,a.y*S.zoom,a.w*S.zoom,a.h*S.zoom);}if(i===S.selected){const b=bbox(a);octx.globalAlpha=1;octx.strokeStyle='#1683ff';octx.lineWidth=2;octx.setLineDash([5,4]);octx.strokeRect(b.x*S.zoom,b.y*S.zoom,b.w*S.zoom,b.h*S.zoom);}octx.restore();}}
function bbox(a){if(a.type==='text')return{x:a.x,y:a.y,w:Math.max(30,a.text.length*a.size*.55),h:a.size*1.3};if(a.type==='image')return{x:a.x,y:a.y,w:a.w,h:a.h};const xs=a.points.map(q=>q.x),ys=a.points.map(q=>q.y),pad=(a.width||1);return{x:Math.min(...xs)-pad,y:Math.min(...ys)-pad,w:Math.max(...xs)-Math.min(...xs)+pad*2,h:Math.max(...ys)-Math.min(...ys)+pad*2}}
function pos(ev){const r=E.overlay.getBoundingClientRect();return{x:(ev.clientX-r.left)/S.zoom,y:(ev.clientY-r.top)/S.zoom}}
function hit(pt){const anns=page().annotations;for(let i=anns.length-1;i>=0;i--){const b=bbox(anns[i]);if(pt.x>=b.x&&pt.x<=b.x+b.w&&pt.y>=b.y&&pt.y<=b.y+b.h)return i}return null}
E.overlay.addEventListener('pointerdown',ev=>{if(!hasDoc())return;E.overlay.setPointerCapture?.(ev.pointerId);const pt=pos(ev);if(S.tool==='pan'){S.drag={type:'pan',x:ev.clientX,y:ev.clientY,sx:E.scroll.scrollLeft,sy:E.scroll.scrollTop};return}if(S.tool==='text'){S.pendingText=pt;E.textInput.value='';E.textDialog.showModal?E.textDialog.showModal():null;return}if(S.tool==='select'){const i=hit(pt);S.selected=i;if(i!=null){saveUndo();S.drag={type:'move',start:pt,orig:clone(page().annotations[i])}}drawOverlay();updateUI();return}if(S.tool==='erase'){const i=hit(pt);if(i!=null){saveUndo();page().annotations.splice(i,1);S.selected=null;drawOverlay();updateUI()}return}if(S.tool==='pen'||S.tool==='highlight'){saveUndo();S.currentStroke={type:S.tool==='highlight'?'highlight':'stroke',color:S.tool==='highlight'?'#ffff00':E.color.value,width:Number(S.tool==='highlight'?E.highW.value:E.penW.value)||3,points:[pt]};page().annotations.push(S.currentStroke);drawOverlay();}});
E.overlay.addEventListener('pointermove',ev=>{if(!S.drag&&!S.currentStroke)return;const pt=pos(ev);if(S.currentStroke){S.currentStroke.points.push(pt);drawOverlay();return}if(S.drag?.type==='pan'){E.scroll.scrollLeft=S.drag.sx-(ev.clientX-S.drag.x);E.scroll.scrollTop=S.drag.sy-(ev.clientY-S.drag.y);return}if(S.drag?.type==='move'&&S.selected!=null){const dx=pt.x-S.drag.start.x,dy=pt.y-S.drag.start.y,a=clone(S.drag.orig);if(a.points)a.points=a.points.map(q=>({x:q.x+dx,y:q.y+dy}));else{a.x+=dx;a.y+=dy}page().annotations[S.selected]=a;drawOverlay();}});
function pointerUp(){if(S.currentStroke){S.currentStroke=null;scheduleRecovery()}if(S.drag){S.drag=null;scheduleRecovery()}}
E.overlay.addEventListener('pointerup',pointerUp);E.overlay.addEventListener('pointercancel',pointerUp);
E.textForm.addEventListener('submit',e=>{e.preventDefault();const text=E.textInput.value;if(text&&S.pendingText){saveUndo();page().annotations.push({type:'text',x:S.pendingText.x,y:S.pendingText.y,text,color:E.color.value,size:Number(E.textSize.value)||18});scheduleRecovery()}S.pendingText=null;E.textDialog.close?.();drawOverlay();updateUI()});E.cancelText.onclick=()=>{S.pendingText=null;E.textDialog.close?.()};
E.imageBtn.onclick=()=>E.imageInput.click();E.imageInput.onchange=()=>{const f=E.imageInput.files[0];E.imageInput.value='';if(!f)return;const url=URL.createObjectURL(f),img=new Image();img.onload=()=>{saveUndo();const p=page(),w=p.width*.35,h=w*(img.height/img.width);p.annotations.push({type:'image',x:p.width*.15,y:p.height*.15,w,h,img,dataUrl:url});drawOverlay();scheduleRecovery()};img.src=url};
E.undo.onclick=()=>{if(!S.undo.length)return;S.redo.push(clone(S.pages));S.pages=S.undo.pop();S.selected=null;render();scheduleRecovery()};E.redo.onclick=()=>{if(!S.redo.length)return;S.undo.push(clone(S.pages));S.pages=S.redo.pop();S.selected=null;render();scheduleRecovery()};E.deleteSel.onclick=()=>{if(S.selected==null)return;saveUndo();page().annotations.splice(S.selected,1);S.selected=null;drawOverlay();updateUI();scheduleRecovery()};E.clear.onclick=()=>{if(!hasDoc()||!page().annotations.length)return;if(confirm('Delete all added edits on this page?')){saveUndo();page().annotations=[];S.selected=null;drawOverlay();updateUI();scheduleRecovery()}};
E.prev.onclick=()=>{if(S.page>0){S.page--;S.selected=null;render()}};E.next.onclick=()=>{if(S.page<S.pages.length-1){S.page++;S.selected=null;render()}};E.addPage.onclick=()=>{if(!hasDoc())return;saveUndo();const p=page();S.pages.splice(S.page+1,0,{kind:'blank',width:p.width,height:p.height,rotation:0,annotations:[]});S.page++;S.fitMode=true;render()};E.delPage.onclick=()=>{if(S.pages.length<=1)return;if(confirm('Delete current page?')){saveUndo();S.pages.splice(S.page,1);S.page=Math.min(S.page,S.pages.length-1);S.fitMode=true;render()}};
function changeZoom(mult){S.fitMode=false;S.zoom=Math.max(.1,Math.min(4,S.zoom*mult));render()}E.zoomIn.onclick=()=>changeZoom(1.15);E.zoomOut.onclick=()=>changeZoom(1/1.15);E.applyZoom.onclick=()=>{S.fitMode=false;S.zoom=Math.max(.1,Math.min(4,(Number(E.zoomInput.value)||100)/100));render()};E.fit.onclick=()=>{S.fitMode=true;render()};
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(hasDoc()&&S.fitMode)render()},120)});addEventListener('orientationchange',()=>setTimeout(()=>{if(hasDoc()){S.fitMode=true;render()}},250));
async function exportPdf(){if(!hasDoc())return;try{toast('Preparing PDF…');const {PDFDocument,rgb,StandardFonts}=await ensurePdfLib();let out;if(S.sourceBytes)out=await PDFDocument.load(S.sourceBytes.slice());else out=await PDFDocument.create();if(!S.sourceBytes){for(const p of S.pages)out.addPage([p.width,p.height]);}else{while(out.getPageCount()<S.pages.length){const p=S.pages[out.getPageCount()];out.addPage([p.width,p.height]);}}const font=await out.embedFont(StandardFonts.Helvetica);for(let i=0;i<S.pages.length;i++){const st=S.pages[i],pg=out.getPage(i);const H=pg.getHeight();for(const a of st.annotations){if(a.type==='text'){const c=hexRgb(a.color);pg.drawText(a.text,{x:a.x,y:H-a.y-a.size,size:a.size,font,color:rgb(c.r,c.g,c.b),lineHeight:a.size*1.2});}else if(a.type==='stroke'||a.type==='highlight'){const c=hexRgb(a.color);for(let j=1;j<a.points.length;j++){const A=a.points[j-1],B=a.points[j];pg.drawLine({start:{x:A.x,y:H-A.y},end:{x:B.x,y:H-B.y},thickness:a.width,color:rgb(c.r,c.g,c.b),opacity:a.type==='highlight'?.35:1});}}else if(a.type==='image'&&a.img){try{const blob=await fetch(a.img.src).then(r=>r.arrayBuffer());let emb;try{emb=await out.embedPng(blob)}catch(_){emb=await out.embedJpg(blob)}pg.drawImage(emb,{x:a.x,y:H-a.y-a.h,width:a.w,height:a.h});}catch(_){}}}}
const bytes=await out.save(),blob=new Blob([bytes],{type:'application/pdf'});const file=new File([blob],S.filename,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[file]})&&/iPad|iPhone|iPod/.test(navigator.userAgent)){try{await navigator.share({files:[file],title:S.filename});await clearRecovery();toast('PDF shared.');return}catch(e){if(e.name==='AbortError')return;}}
const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=S.filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);await clearRecovery();toast('PDF saved.');}catch(err){console.error(err);toast('Could not save PDF.')}}
function hexRgb(h){h=(h||'#000000').replace('#','');const n=parseInt(h,16);return{r:((n>>16)&255)/255,g:((n>>8)&255)/255,b:(n&255)/255}}
E.saveBtn.onclick=exportPdf;
// IndexedDB revolving recovery: one slot, overwritten rather than accumulated.
const DB='simple-pdf-editor',STORE='recovery',KEY='current';function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}async function putRecovery(){if(!hasDoc())return;try{const db=await openDb(),tx=db.transaction(STORE,'readwrite');const serial=S.pages.map(p=>({...p,annotations:p.annotations.map(a=>{const z={...a};delete z.img;delete z.dataUrl;return z})}));tx.objectStore(STORE).put({time:Date.now(),filename:S.filename,source:S.sourceBytes?Array.from(S.sourceBytes):null,pages:serial,page:S.page},KEY)}catch(_){}}let recTimer;function scheduleRecovery(){clearTimeout(recTimer);recTimer=setTimeout(putRecovery,700)}async function clearRecovery(){try{const db=await openDb();db.transaction(STORE,'readwrite').objectStore(STORE).delete(KEY)}catch(_){}}
async function offerRecovery(){try{const db=await openDb();const req=db.transaction(STORE).objectStore(STORE).get(KEY);req.onsuccess=async()=>{const r=req.result;if(!r)return;if(Date.now()-r.time>30*86400000){clearRecovery();return}if(confirm(`Recover unsaved PDF "${r.filename}"?`)){S.sourceBytes=r.source?new Uint8Array(r.source):null;S.pages=r.pages||[];S.page=Math.min(r.page||0,S.pages.length-1);S.filename=r.filename||'edited.pdf';if(S.sourceBytes){const pdfjs=await ensurePdfJs();S.pdfDoc=await pdfjs.getDocument({data:S.sourceBytes.slice()}).promise}else S.pdfDoc=null;showEditor();S.fitMode=true;render();updateUI();}}}catch(_){}}
// Keyboard shortcuts desktop only.
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();exportPdf()}else if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();E.undo.click()}else if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();E.redo.click()}else if(mod&&e.key==='0'){e.preventDefault();E.fit.click()}else if(e.key==='Delete')E.deleteSel.click();else if(!mod&&'speht'.includes(e.key.toLowerCase())){const map={s:'select',p:'pen',e:'erase',h:'highlight',t:'text'};setTool(map[e.key.toLowerCase()])}});
showEmpty();updateUI();offerRecovery();
})();
