(() => {
'use strict';
const $=id=>document.getElementById(id);
const el={
 newBtn:$('newBtn'),importBtn:$('importBtn'),saveBtn:$('saveBtn'),addPageBtn:$('addPageBtn'),delPageBtn:$('delPageBtn'),prevBtn:$('prevBtn'),nextBtn:$('nextBtn'),pageLabel:$('pageLabel'),
 imageBtn:$('imageBtn'),colorPicker:$('colorPicker'),undoBtn:$('undoBtn'),redoBtn:$('redoBtn'),deleteSelectedBtn:$('deleteSelectedBtn'),clearPageBtn:$('clearPageBtn'),
 penWidth:$('penWidth'),highlightWidth:$('highlightWidth'),eraserWidth:$('eraserWidth'),textSize:$('textSize'),zoomOutBtn:$('zoomOutBtn'),zoomInBtn:$('zoomInBtn'),zoomInput:$('zoomInput'),applyZoomBtn:$('applyZoomBtn'),fitBtn:$('fitBtn'),zoomLabel:$('zoomLabel'),toolLabel:$('toolLabel'),
 workspace:$('workspace'),emptyState:$('emptyState'),scrollArea:$('scrollArea'),pageStage:$('pageStage'),pdfCanvas:$('pdfCanvas'),overlayCanvas:$('overlayCanvas'),status:$('status'),selectionStatus:$('selectionStatus'),pdfInput:$('pdfInput'),imageInput:$('imageInput'),
 emptyNewBtn:$('emptyNewBtn'),emptyImportBtn:$('emptyImportBtn'),newDialog:$('newDialog'),newForm:$('newForm'),pageSizeSelect:$('pageSizeSelect'),createPdfBtn:$('createPdfBtn'),textDialog:$('textDialog'),textForm:$('textForm'),textInput:$('textInput'),cancelTextBtn:$('cancelTextBtn'),toolsToggleBtn:$('toolsToggleBtn'),toolbarWrap:$('toolbarWrap'),toast:$('toast')
};
const missing=Object.entries(el).filter(([,v])=>!v).map(([k])=>k);if(missing.length){console.error('Missing UI elements:',missing);return;}
const pdfCtx=el.pdfCanvas.getContext('2d');const overCtx=el.overlayCanvas.getContext('2d');
const state={sourceBytes:null,pdfjsDoc:null,pages:[],pageIndex:0,tool:'select',fitMode:true,manualScale:1,renderSeq:0,drawing:null,history:[],redo:[],fileName:'edited.pdf',pendingText:null,imageData:null,pointers:new Map(),pinchStart:null};
let pdfJsPromise=null,pdfLibPromise=null,workerUrl='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
function loadScript(url){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=url;s.onload=res;s.onerror=rej;document.head.appendChild(s);});}
async function ensurePdfJs(){if(window.pdfjsLib)return window.pdfjsLib;if(!pdfJsPromise)pdfJsPromise=(async()=>{for(const u of ['https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js']){try{await loadScript(u);if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc=workerUrl;return window.pdfjsLib;}}catch(e){}}throw new Error('PDF.js could not load');})();return pdfJsPromise;}
async function ensurePdfLib(){if(window.PDFLib)return window.PDFLib;if(!pdfLibPromise)pdfLibPromise=(async()=>{for(const u of ['https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js','https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js']){try{await loadScript(u);if(window.PDFLib)return window.PDFLib;}catch(e){}}throw new Error('pdf-lib could not load');})();return pdfLibPromise;}
function toast(msg){el.toast.textContent=msg;el.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.add('hidden'),2400)}
function current(){return state.pages[state.pageIndex]}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function enableEditor(on){for(const b of [el.saveBtn,el.addPageBtn,el.delPageBtn,el.prevBtn,el.nextBtn,el.imageBtn,el.clearPageBtn,el.zoomOutBtn,el.zoomInBtn,el.applyZoomBtn,el.fitBtn])b.disabled=!on;el.emptyState.classList.toggle('hidden',on);el.scrollArea.classList.toggle('hidden',!on)}
function pageSizes(name){return {'Letter - Portrait':[612,792],'Letter - Landscape':[792,612],'A4 - Portrait':[595,842],'A4 - Landscape':[842,595],'Square':[612,612]}[name]||[612,792]}
function snapshot(){state.history.push(JSON.stringify(state.pages));if(state.history.length>40)state.history.shift();state.redo=[];refreshButtons();scheduleRecovery()}
function undo(){if(!state.history.length)return;state.redo.push(JSON.stringify(state.pages));state.pages=JSON.parse(state.history.pop());state.pageIndex=clamp(state.pageIndex,0,state.pages.length-1);render();refreshButtons();scheduleRecovery()}
function redo(){if(!state.redo.length)return;state.history.push(JSON.stringify(state.pages));state.pages=JSON.parse(state.redo.pop());state.pageIndex=clamp(state.pageIndex,0,state.pages.length-1);render();refreshButtons();scheduleRecovery()}
function refreshButtons(){const on=state.pages.length>0;enableEditor(on);el.prevBtn.disabled=!on||state.pageIndex<=0;el.nextBtn.disabled=!on||state.pageIndex>=state.pages.length-1;el.delPageBtn.disabled=!on||state.pages.length<=1;el.undoBtn.disabled=!state.history.length;el.redoBtn.disabled=!state.redo.length;el.deleteSelectedBtn.disabled=true;el.pageLabel.textContent=on?`Page ${state.pageIndex+1} / ${state.pages.length}`:'Page 0 / 0';el.toolLabel.textContent=`Tool: ${state.tool[0].toUpperCase()+state.tool.slice(1)}`}
function setTool(t){state.tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));refreshButtons();el.overlayCanvas.style.touchAction=t==='pan'?'pan-x pan-y':'none'}
function baseViewportDims(pg){if(pg.rotation%180===0)return {w:pg.width,h:pg.height};return {w:pg.height,h:pg.width}}
function calculateScale(pg){if(!state.fitMode)return state.manualScale;const d=baseViewportDims(pg);const cs=getComputedStyle(el.scrollArea);const padX=parseFloat(cs.paddingLeft)+parseFloat(cs.paddingRight);const padY=parseFloat(cs.paddingTop)+parseFloat(cs.paddingBottom);const aw=Math.max(80,el.scrollArea.clientWidth-padX-2);const ah=Math.max(80,el.scrollArea.clientHeight-padY-2);return Math.max(.05,Math.min(aw/d.w,ah/d.h));}
async function render(){if(!state.pages.length)return;const seq=++state.renderSeq;const pg=current();const scale=calculateScale(pg);const dims=baseViewportDims(pg);const cssW=Math.max(1,dims.w*scale),cssH=Math.max(1,dims.h*scale);const dpr=Math.min(window.devicePixelRatio||1,2.5);
 el.pageStage.style.width=`${cssW}px`;el.pageStage.style.height=`${cssH}px`;
 for(const c of [el.pdfCanvas,el.overlayCanvas]){c.width=Math.max(1,Math.round(cssW*dpr));c.height=Math.max(1,Math.round(cssH*dpr));c.style.width=`${cssW}px`;c.style.height=`${cssH}px`}
 pdfCtx.setTransform(1,0,0,1,0,0);pdfCtx.clearRect(0,0,el.pdfCanvas.width,el.pdfCanvas.height);pdfCtx.fillStyle='#fff';pdfCtx.fillRect(0,0,el.pdfCanvas.width,el.pdfCanvas.height);
 if(pg.sourceIndex!=null&&state.pdfjsDoc){const src=await state.pdfjsDoc.getPage(pg.sourceIndex+1);if(seq!==state.renderSeq)return;const viewport=src.getViewport({scale,rotation:pg.rotation});await src.render({canvasContext:pdfCtx,viewport,transform:dpr!==1?[dpr,0,0,dpr,0,0]:null}).promise}else{pdfCtx.setTransform(dpr,0,0,dpr,0,0);pdfCtx.fillStyle='#fff';pdfCtx.fillRect(0,0,cssW,cssH)}
 drawOverlay(scale,dpr);state.manualScale=scale;el.zoomInput.value=Math.round(scale*100);el.zoomLabel.textContent=`Zoom ${Math.round(scale*100)}%`;el.status.textContent=`${pg.annotations.length} editable edit(s). Recovery autosave is ON.`;refreshButtons()}
function drawOverlay(scale,dpr){overCtx.setTransform(dpr,0,0,dpr,0,0);overCtx.clearRect(0,0,el.overlayCanvas.width/dpr,el.overlayCanvas.height/dpr);const pg=current();if(!pg)return;for(const a of pg.annotations){if(a.type==='pen'||a.type==='highlight'){overCtx.save();overCtx.strokeStyle=a.color;overCtx.globalAlpha=a.type==='highlight'?.35:1;overCtx.lineWidth=a.width*scale;overCtx.lineCap='round';overCtx.lineJoin='round';overCtx.beginPath();a.points.forEach((p,i)=>i?overCtx.lineTo(p.x*scale,p.y*scale):overCtx.moveTo(p.x*scale,p.y*scale));overCtx.stroke();overCtx.restore()}else if(a.type==='text'){overCtx.save();overCtx.fillStyle=a.color;overCtx.font=`${a.size*scale}px Arial`;overCtx.textBaseline='top';String(a.text).split('\n').forEach((line,i)=>overCtx.fillText(line,a.x*scale,(a.y+i*a.size*1.2)*scale));overCtx.restore()}else if(a.type==='image'&&a.img){overCtx.drawImage(a.img,a.x*scale,a.y*scale,a.w*scale,a.h*scale)}}}
function pointFromEvent(e){const r=el.overlayCanvas.getBoundingClientRect();const pg=current();const s=calculateScale(pg);return{x:clamp((e.clientX-r.left)/s,0,baseViewportDims(pg).w),y:clamp((e.clientY-r.top)/s,0,baseViewportDims(pg).h)}}
async function importPdf(file){try{const pdfjs=await ensurePdfJs();const bytes=new Uint8Array(await file.arrayBuffer());state.sourceBytes=bytes;state.pdfjsDoc=await pdfjs.getDocument({data:bytes.slice()}).promise;state.pages=[];for(let i=0;i<state.pdfjsDoc.numPages;i++){const p=await state.pdfjsDoc.getPage(i+1);const v=p.getViewport({scale:1});state.pages.push({sourceIndex:i,width:v.width,height:v.height,rotation:0,annotations:[]})}state.pageIndex=0;state.fitMode=true;state.fileName=file.name.replace(/\.pdf$/i,'')+'-edited.pdf';state.history=[];state.redo=[];enableEditor(true);await render();scheduleRecovery();toast('PDF opened')}catch(e){console.error(e);toast('Could not open PDF. Check internet/CDN access.')}}
async function newPdf(){const [w,h]=pageSizes(el.pageSizeSelect.value);state.sourceBytes=null;state.pdfjsDoc=null;state.pages=[{sourceIndex:null,width:w,height:h,rotation:0,annotations:[]}];state.pageIndex=0;state.fitMode=true;state.fileName='new-pdf.pdf';state.history=[];state.redo=[];enableEditor(true);await render();scheduleRecovery()}
async function exportPdf(){try{const {PDFDocument,rgb,degrees}=await ensurePdfLib();const out=await PDFDocument.create();let src=null;if(state.sourceBytes)src=await PDFDocument.load(state.sourceBytes.slice());for(const pg of state.pages){let op;if(pg.sourceIndex!=null&&src){const [copied]=await out.copyPages(src,[pg.sourceIndex]);out.addPage(copied);op=copied}else op=out.addPage([pg.width,pg.height]);if(pg.rotation)op.setRotation(degrees(pg.rotation));for(const a of pg.annotations){if(a.type==='text'){const c=hexRgb(a.color);op.drawText(a.text,{x:a.x,y:op.getHeight()-a.y-a.size,size:a.size,color:rgb(c.r,c.g,c.b),lineHeight:a.size*1.2})}else if(a.type==='pen'||a.type==='highlight'){const c=hexRgb(a.color);for(let i=1;i<a.points.length;i++){const p0=a.points[i-1],p1=a.points[i];op.drawLine({start:{x:p0.x,y:op.getHeight()-p0.y},end:{x:p1.x,y:op.getHeight()-p1.y},thickness:a.width,color:rgb(c.r,c.g,c.b),opacity:a.type==='highlight'?.35:1})}}else if(a.type==='image'&&a.dataUrl){const arr=await (await fetch(a.dataUrl)).arrayBuffer();const emb=a.dataUrl.startsWith('data:image/png')?await out.embedPng(arr):await out.embedJpg(arr);op.drawImage(emb,{x:a.x,y:op.getHeight()-a.y-a.h,width:a.w,height:a.h})}}}const bytes=await out.save();const blob=new Blob([bytes],{type:'application/pdf'});const file=new File([blob],state.fileName,{type:'application/pdf'});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:state.fileName});await clearRecovery();toast('PDF exported');return}catch(e){if(e.name!=='AbortError')console.warn(e)}}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=state.fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);await clearRecovery();toast('PDF exported')}catch(e){console.error(e);toast('Export failed')}}
function hexRgb(h){const n=parseInt(h.replace('#',''),16);return{r:((n>>16)&255)/255,g:((n>>8)&255)/255,b:(n&255)/255}}
function addPage(){snapshot();const p=current();state.pages.splice(state.pageIndex+1,0,{sourceIndex:null,width:p.width,height:p.height,rotation:0,annotations:[]});state.pageIndex++;state.fitMode=true;render()}
function deletePage(){if(state.pages.length<=1)return;snapshot();state.pages.splice(state.pageIndex,1);state.pageIndex=Math.min(state.pageIndex,state.pages.length-1);state.fitMode=true;render()}
function clearPage(){if(!current()?.annotations.length)return;snapshot();current().annotations=[];render()}
function navigate(d){const ni=clamp(state.pageIndex+d,0,state.pages.length-1);if(ni!==state.pageIndex){state.pageIndex=ni;state.fitMode=true;render()}}
function zoom(f){state.fitMode=false;state.manualScale=clamp((state.manualScale||calculateScale(current()))*f,.1,4);render()}
function applyZoom(){state.fitMode=false;state.manualScale=clamp((Number(el.zoomInput.value)||100)/100,.1,4);render()}
function fit(){state.fitMode=true;render()}
function rotatePage(){snapshot();current().rotation=(current().rotation+90)%360;state.fitMode=true;render()}
function addTextAt(p,text){snapshot();current().annotations.push({type:'text',x:p.x,y:p.y,text,color:el.colorPicker.value,size:clamp(Number(el.textSize.value)||18,6,144)});render()}
function handlePointerDown(e){if(!state.pages.length)return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2){const a=[...state.pointers.values()];state.pinchStart={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale:state.manualScale||calculateScale(current())};return}if(state.tool==='text'){state.pendingText=pointFromEvent(e);if(el.textDialog.showModal)el.textDialog.showModal();else el.textDialog.setAttribute('open','');return}if(state.tool==='pen'||state.tool==='highlight'){e.preventDefault();snapshot();const p=pointFromEvent(e);const a={type:state.tool,points:[p],color:state.tool==='highlight'?'#ffff00':el.colorPicker.value,width:state.tool==='highlight'?Number(el.highlightWidth.value)||16:Number(el.penWidth.value)||3};current().annotations.push(a);state.drawing=a;el.overlayCanvas.setPointerCapture?.(e.pointerId);drawOverlay(calculateScale(current()),Math.min(window.devicePixelRatio||1,2.5))}else if(state.tool==='erase'){e.preventDefault();eraseAt(pointFromEvent(e))}}
function handlePointerMove(e){if(state.pointers.has(e.pointerId))state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2&&state.pinchStart){e.preventDefault();const a=[...state.pointers.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);state.fitMode=false;state.manualScale=clamp(state.pinchStart.scale*(d/state.pinchStart.dist),.1,4);render();return}if(state.drawing&&(state.tool==='pen'||state.tool==='highlight')){e.preventDefault();state.drawing.points.push(pointFromEvent(e));drawOverlay(calculateScale(current()),Math.min(window.devicePixelRatio||1,2.5))}else if(state.tool==='erase'&&e.buttons)eraseAt(pointFromEvent(e))}
function handlePointerUp(e){state.pointers.delete(e.pointerId);if(state.pointers.size<2)state.pinchStart=null;if(state.drawing){state.drawing=null;scheduleRecovery()}}
function eraseAt(p){const r=(Number(el.eraserWidth.value)||20)/2;const anns=current().annotations;for(let i=anns.length-1;i>=0;i--){const a=anns[i];let hit=false;if(a.type==='text')hit=p.x>=a.x&&p.x<=a.x+a.text.length*a.size*.6&&p.y>=a.y&&p.y<=a.y+a.size*1.4;else if(a.points)hit=a.points.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<=r+a.width/2);if(hit){snapshot();anns.splice(i,1);render();return}}}
function importImage(file){const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{snapshot();const pg=current();const w=pg.width*.35,h=w*(img.height/img.width);current().annotations.push({type:'image',x:pg.width*.15,y:pg.height*.15,w,h,dataUrl:fr.result,img});render();scheduleRecovery()};img.src=fr.result};fr.readAsDataURL(file)}
function hydrateImages(){for(const pg of state.pages)for(const a of pg.annotations||[])if(a.type==='image'&&a.dataUrl&&!a.img){const img=new Image();img.onload=()=>render();img.src=a.dataUrl;a.img=img}}
// IndexedDB revolving recovery slot
const DB='SimplePDFEditorRecovery',STORE='drafts',KEY='current';let saveTimer;
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function scheduleRecovery(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{if(!state.pages.length)return;try{const db=await openDb();const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({savedAt:Date.now(),fileName:state.fileName,sourceBytes:state.sourceBytes?Array.from(state.sourceBytes):null,pages:state.pages},KEY)}catch(e){console.warn('Recovery save failed',e)}},700)}
async function clearRecovery(){try{const db=await openDb();db.transaction(STORE,'readwrite').objectStore(STORE).delete(KEY)}catch(e){}}
async function offerRecovery(){try{const db=await openDb();const req=db.transaction(STORE).objectStore(STORE).get(KEY);req.onsuccess=async()=>{const d=req.result;if(!d)return;if(Date.now()-d.savedAt>30*864e5){clearRecovery();return}if(confirm(`Recover unsaved PDF "${d.fileName}"?`)){state.fileName=d.fileName;state.pages=d.pages||[];state.sourceBytes=d.sourceBytes?new Uint8Array(d.sourceBytes):null;if(state.sourceBytes){const pdfjs=await ensurePdfJs();state.pdfjsDoc=await pdfjs.getDocument({data:state.sourceBytes.slice()}).promise}hydrateImages();state.pageIndex=0;state.fitMode=true;enableEditor(true);render()}}}catch(e){}}
// UI wiring
el.newBtn.onclick=el.emptyNewBtn.onclick=()=>el.newDialog.showModal?el.newDialog.showModal():el.newDialog.setAttribute('open','');
el.createPdfBtn.onclick=e=>{e.preventDefault();el.newDialog.close?.();newPdf()};el.importBtn.onclick=el.emptyImportBtn.onclick=()=>el.pdfInput.click();el.pdfInput.onchange=()=>{const f=el.pdfInput.files[0];if(f)importPdf(f);el.pdfInput.value=''};el.saveBtn.onclick=exportPdf;el.addPageBtn.onclick=addPage;el.delPageBtn.onclick=deletePage;el.prevBtn.onclick=()=>navigate(-1);el.nextBtn.onclick=()=>navigate(1);el.undoBtn.onclick=undo;el.redoBtn.onclick=redo;el.clearPageBtn.onclick=clearPage;el.zoomInBtn.onclick=()=>zoom(1.15);el.zoomOutBtn.onclick=()=>zoom(1/1.15);el.applyZoomBtn.onclick=applyZoom;el.fitBtn.onclick=fit;el.imageBtn.onclick=()=>el.imageInput.click();el.imageInput.onchange=()=>{const f=el.imageInput.files[0];if(f)importImage(f);el.imageInput.value=''};document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
el.overlayCanvas.addEventListener('pointerdown',handlePointerDown,{passive:false});el.overlayCanvas.addEventListener('pointermove',handlePointerMove,{passive:false});el.overlayCanvas.addEventListener('pointerup',handlePointerUp);el.overlayCanvas.addEventListener('pointercancel',handlePointerUp);
el.textForm.onsubmit=e=>{e.preventDefault();const t=el.textInput.value;if(t&&state.pendingText)addTextAt(state.pendingText,t);state.pendingText=null;el.textInput.value='';el.textDialog.close?.()};el.cancelTextBtn.onclick=()=>{state.pendingText=null;el.textDialog.close?.()};
el.toolsToggleBtn.onclick=()=>{const open=el.toolbarWrap.classList.toggle('open');el.toolsToggleBtn.setAttribute('aria-expanded',String(open));el.toolsToggleBtn.textContent=open?'Hide Tools':'Tools';setTimeout(()=>{if(state.fitMode&&state.pages.length)render()},50)};
let resizeTimer;const refit=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state.fitMode&&state.pages.length)render()},120)};window.addEventListener('resize',refit);window.addEventListener('orientationchange',()=>setTimeout(refit,250));if(window.visualViewport)window.visualViewport.addEventListener('resize',refit);
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(k==='s'&&!e.ctrlKey&&!e.metaKey)setTool('select');else if(k==='p')setTool('pen');else if(k==='e')setTool('erase');else if(k==='h')setTool('highlight');else if(k==='t')setTool('text');else if((e.ctrlKey||e.metaKey)&&k==='s'){e.preventDefault();exportPdf()}else if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();undo()}else if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();redo()}else if(e.key==='PageUp')navigate(-1);else if(e.key==='PageDown')navigate(1);else if((e.ctrlKey||e.metaKey)&&k==='0'){e.preventDefault();fit()}else if(k==='r'&&state.pages.length)rotatePage()});
enableEditor(false);refreshButtons();offerRecovery();
})();
